/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "camera_fb_t.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CAMERA_FB_TYPE_Camera_fb_t, CAMERA_FB_TYPE_Camera_fb_t, AUTO)



